### ISSUE TITLE
[Feature]: Docker Image

### ISSUE THREAD

**Issue by avoonix** [avoonix/material-e621#3]
Create a docker image for easier self hosting #2

**Comment by avoonix** [comment]
`npm run dev` is for the unoptimized development build, which sadly still doesn't work in Firefox (and some other browsers). Serving the output from `npm run build` should work for everywhere.

**Comment by avoonix** [comment]
> is it possible to automatically store a backup of the indexed-db on the server ? ( maybe with https://www.npmjs.com/package/vite-plugin-fs ? )

Yes, since both https://github.com/avoonix/material-e621/blob/bdbdea12f6256572aeeb2fb712767c6371bf1cee/src/services/PersistanceService.ts#L29-L32 and https://github.com/avoonix/material-e621/blob/bdbdea12f6256572aeeb2fb712767c6371bf1cee/src/services/PersistanceService.ts#L33-L43 are async, you can just put network calls in there if you wish (maybe also debounce it). But that is not something I'd like to support out of the box.

**Comment by avoonix** [comment]
Thanks for all the input. I used your dockerfile as starting point, but ended up changing quite a bit. Let me know if any of the changes in cc751c8 or 534b7b7 don't work for you. 

https://github.com/avoonix/material-e621/pkgs/container/material-e621

Instructions:

```bash
sudo docker run -d -p 8080:80 ghcr.io/avoonix/material-e621:latest
```
or

```yml
version: "3"
services:
  app:
    image: ghcr.io/avoonix/material-e621:latest
    # if you want to build it yourself, replace `image` with `build`
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:80
```
